version: '3.1'
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    volumes: 
        - ./mydb:/var/lib/mysql
    environment:
        MYSQL_ROOT_PASSWORD: '12345'
        MYSQL_DATABASE: "food_stories"
    
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  
  web:
    build: .
    restart: "always"
    ports:
      - "8000:8000"
    command: python manage.py runserver 0.0.0.0:8000